import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-company-details',
  templateUrl: './company-details.component.html',
  styleUrls: ['./company-details.component.css']
})
export class CompanyDetailsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void 
  {

  }

  companies = [
    {
      name: 'Google',
      ctc: '30 LPA',
      examDate: '2025-07-15',
      role: 'Software Engineer',
      eligibility: '7.5+ CGPA, No backlogs',
      previousPlacements: 5,
      selectionProcess: 'Aptitude + Coding + Interview',
      jobLocation: 'Bangalore',
      bond: 'No',
    },
    {
      name: 'Amazon',
      ctc: '28 LPA',
      examDate: '2025-08-10',
      role: 'Cloud Engineer',
      eligibility: '7.0+ CGPA, No backlogs',
      previousPlacements: 8,
      selectionProcess: 'Online Test + 2 Rounds Interview',
      jobLocation: 'Hyderabad',
      bond: 'No',
    },
    {
      name: 'TCS Digital',
      ctc: '7 LPA',
      examDate: '2025-06-25',
      role: 'Software Developer',
      eligibility: '6.0+ CGPA, Max 1 backlog',
      previousPlacements: 15,
      selectionProcess: 'Online Test + Interview',
      jobLocation: 'Multiple Locations',
      bond: 'Yes, 2 Years',
    },
    {
      name: 'Microsoft',
      ctc: '40 LPA',
      examDate: '2025-07-20',
      role: 'Software Development Engineer',
      eligibility: '8+ CGPA, No backlogs',
      previousPlacements: 4,
      selectionProcess: 'Aptitude + Coding + 2 Interviews',
      jobLocation: 'Hyderabad',
      bond: 'No',
    },
    {
      name: 'Infosys',
      ctc: '5 LPA',
      examDate: '2025-06-30',
      role: 'System Engineer',
      eligibility: '6+ CGPA, No backlogs',
      previousPlacements: 20,
      selectionProcess: 'Online Test + Interview',
      jobLocation: 'Multiple Locations',
      bond: 'Yes, 1 Year',
    },
    {
      name: 'Wipro',
      ctc: '4.5 LPA',
      examDate: '2025-07-05',
      role: 'Project Engineer',
      eligibility: '6+ CGPA, Max 1 backlog',
      previousPlacements: 18,
      selectionProcess: 'Aptitude + Technical Interview',
      jobLocation: 'Multiple Locations',
      bond: 'Yes, 1.5 Years',
    },
    {
      name: 'Adobe',
      ctc: '32 LPA',
      examDate: '2025-07-10',
      role: 'Software Engineer',
      eligibility: '7.5+ CGPA, No backlogs',
      previousPlacements: 6,
      selectionProcess: 'Online Test + 3 Rounds Interview',
      jobLocation: 'Bangalore',
      bond: 'No',
    },
    // {
    //   name: 'Flipkart',
    //   ctc: '26 LPA',
    //   examDate: '2025-07-18',
    //   role: 'Data Scientist',
    //   eligibility: '7+ CGPA, No backlogs',
    //   previousPlacements: 7,
    //   selectionProcess: 'Aptitude + Coding + Interview',
    //   jobLocation: 'Bangalore',
    //   bond: 'No',
    // },
    // {
    //   name: 'Capgemini',
    //   ctc: '6 LPA',
    //   examDate: '2025-06-28',
    //   role: 'Software Engineer',
    //   eligibility: '6+ CGPA, No backlogs',
    //   previousPlacements: 25,
    //   selectionProcess: 'Online Test + HR & Technical Interview',
    //   jobLocation: 'Multiple Locations',
    //   bond: 'Yes, 2 Years',
    // },
    // {
    //   name: 'Cognizant',
    //   ctc: '5.5 LPA',
    //   examDate: '2025-06-22',
    //   role: 'Programmer Analyst',
    //   eligibility: '6+ CGPA, Max 1 backlog',
    //   previousPlacements: 22,
    //   selectionProcess: 'Online Test + Interview',
    //   jobLocation: 'Multiple Locations',
    //   bond: 'Yes, 1.5 Years',
    // },
    // {
    //   name: 'Goldman Sachs',
    //   ctc: '25 LPA',
    //   examDate: '2025-07-12',
    //   role: 'Financial Analyst',
    //   eligibility: '7.5+ CGPA, No backlogs',
    //   previousPlacements: 3,
    //   selectionProcess: 'Aptitude + Case Study + Interview',
    //   jobLocation: 'Bangalore',
    //   bond: 'No',
    // },
    // {
    //   name: 'Oracle',
    //   ctc: '20 LPA',
    //   examDate: '2025-07-08',
    //   role: 'Database Engineer',
    //   eligibility: '7+ CGPA, No backlogs',
    //   previousPlacements: 6,
    //   selectionProcess: 'Online Test + Interview',
    //   jobLocation: 'Hyderabad',
    //   bond: 'No',
    // },
    // {
    //   name: 'Deloitte',
    //   ctc: '12 LPA',
    //   examDate: '2025-07-14',
    //   role: 'Business Analyst',
    //   eligibility: '7+ CGPA, No backlogs',
    //   previousPlacements: 10,
    //   selectionProcess: 'Case Study + Interview',
    //   jobLocation: 'Mumbai',
    //   bond: 'No',
    // },
    // {
    //   name: 'JP Morgan Chase',
    //   ctc: '22 LPA',
    //   examDate: '2025-07-16',
    //   role: 'Software Developer',
    //   eligibility: '7.5+ CGPA, No backlogs',
    //   previousPlacements: 5,
    //   selectionProcess: 'Aptitude + Coding + HR Interview',
    //   jobLocation: 'Bangalore',
    //   bond: 'No',
    // },
    // {
    //   name: 'Accenture',
    //   ctc: '6.5 LPA',
    //   examDate: '2025-06-29',
    //   role: 'Software Developer',
    //   eligibility: '6+ CGPA, No backlogs',
    //   previousPlacements: 30,
    //   selectionProcess: 'Online Test + Technical Interview',
    //   jobLocation: 'Multiple Locations',
    //   bond: 'Yes, 1.5 Years',
    // }
];


}
